# Pothole data sandbox

In [1]:
import duckdb
import pandas as pd

con = duckdb.connect()

# Create a view to the pothole data
RAW_311 = 'data/raw/311_pothole.parquet'
con.sql(f"""
    CREATE OR REPLACE VIEW raw_311 AS
    SELECT * FROM '{RAW_311}'
""")

# Print version
con.sql("SELECT version()").df()

  "version"()
0      v1.5.3

In [2]:
# Describe the table
con.sql("DESCRIBE raw_311").show(max_rows=40)

┌────────────────────────────────┬──────────────────────────────────────────────┬─────────┬─────────┬─────────┬─────────┐
│          column_name           │                 column_type                  │  null   │   key   │ default │  extra  │
│            varchar             │                   varchar                    │ varchar │ varchar │ varchar │ varchar │
├────────────────────────────────┼──────────────────────────────────────────────┼─────────┼─────────┼─────────┼─────────┤
│ unique_key                     │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ created_date                   │ TIMESTAMP                                    │ YES     │ NULL    │ NULL    │ NULL    │
│ closed_date                    │ TIMESTAMP                                    │ YES     │ NULL    │ NULL    │ NULL    │
│ agency                         │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ agency_name                    │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ complaint_type                 │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ descriptor                     │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ incident_zip                   │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ incident_address               │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ street_name                    │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ cross_street_1                 │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ cross_street_2                 │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ address_type                   │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ city                           │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ facility_type                  │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ status                         │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ resolution_description         │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ resolution_action_updated_date │ TIMESTAMP                                    │ YES     │ NULL    │ NULL    │ NULL    │
│ community_board                │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ police_precinct                │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ borough                        │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ open_data_channel_type         │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ park_facility_name             │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ park_borough                   │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ intersection_street_1          │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ intersection_street_2          │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ council_district               │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
│ x_coordinate_state_plane       │ DOUBLE                                       │ YES     │ NULL    │ NULL    │ NULL    │
│ y_coordinate_state_plane       │ DOUBLE                                       │ YES     │ NULL    │ NULL    │ NULL    │
│ latitude                       │ DOUBLE                                       │ YES     │ NULL    │ NULL    │ NULL    │
│ longitude                      │ DOUBLE                                       │ YES     │ NULL    │ NULL    │ NULL    │
│ location                       │ STRUCT("type" VARCHAR, coordinates DOUBLE[]) │ YES     │ NULL    │ NULL    │ NULL    │
│ bbl                            │ VARCHAR                                      │ YES     │ NULL    │ NULL    │ NULL    │
└────────────────────────────────┴──────────────────────────────────────────────┴─────────┴─────────┴─────────┴─────────┘
  33 rows                                                                                                     6 columns

In [3]:
# Basic select everything
con.sql("SELECT COUNT(*) FROM raw_311").df()

   count_star()
0           100

In [5]:
con.sql("""
    SELECT *
    FROM raw_311
    """).df()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,incident_zip,incident_address,street_name,...,park_borough,intersection_street_1,intersection_street_2,council_district,x_coordinate_state_plane,y_coordinate_state_plane,latitude,longitude,location,bbl
0,59478136,2023-11-17 18:08:21,2023-11-21 09:49:00,DOT,Department of Transportation,Street Condition,Pothole,11415,83 AVENUE,83 AVENUE,...,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN
1,59490428,2023-11-18 22:51:56,2023-11-19 19:45:00,DOT,Department of Transportation,Street Condition,Pothole,11236,NaN,NaN,...,BROOKLYN,AVENUE D,EAST 94 STREET,42,1009224.0,175502.0,40.648354,-73.910002,"{'type': 'Point', 'coordinates': [-73.91000217...",NaN
2,59480168,2023-11-16 01:11:15,2023-11-17 19:10:00,DOT,Department of Transportation,Street Condition,Pothole,10001,WEST 35 STREET,WEST 35 STREET,...,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN
3,59485500,2023-11-17 14:45:07,2023-11-18 10:30:00,DOT,Department of Transportation,Street Condition,Pothole,10036,7 AVENUE,7 AVENUE,...,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN
4,59485946,2023-11-18 20:50:35,2023-11-20 08:20:00,DOT,Department of Transportation,Street Condition,Pothole,10128,NaN,NaN,...,MANHATTAN,EAST 90 STREET,YORK AVENUE,05,999412.0,222905.0,40.778486,-73.945255,"{'type': 'Point', 'coordinates': [-73.94525452...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,59515700,2023-11-20 22:21:04,2023-11-21 17:40:00,DOT,Department of Transportation,Street Condition,Pothole,11211,545 METROPOLITAN AVENUE,METROPOLITAN AVENUE,...,BROOKLYN,NaN,NaN,34,997943.0,199437.0,40.714075,-73.950606,"{'type': 'Point', 'coordinates': [-73.95060642...",3027560041
96,59504722,2023-11-20 16:40:52,2023-11-27 12:52:00,DOT,Department of Transportation,Street Condition,Pothole,11106,31 AVENUE,31 AVENUE,...,QUEENS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN
97,59507448,2023-11-20 11:16:15,2023-11-21 10:45:00,DOT,Department of Transportation,Street Condition,Pothole,10019,WEST 49 STREET,WEST 49 STREET,...,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN
98,59501999,2023-11-20 11:18:39,2023-11-22 09:55:00,DOT,Department of Transportation,Street Condition,Pothole,10036,WEST 44 STREET,WEST 44 STREET,...,MANHATTAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN
99,59504120,2023-11-19 23:12:03,2023-11-20 21:40:00,DOT,Department of Transportation,Street Condition,Pothole,10001,151 WEST 34 STREET,WEST 34 STREET,...,MANHATTAN,NaN,NaN,03,987165.0,212710.0,40.750516,-73.989479,"{'type': 'Point', 'coordinates': [-73.98947922...",1008100001