### Testing SQL output from script
Need to run this from here because SQL scripts need to be called from root. Or need to figure out how to send absolute paths?? Ask Claude later, it's low priority

In [1]:
import duckdb
import pandas as pd

con = duckdb.connect()

con.sql("SELECT version()").df()

  "version"()
0      v1.5.3

In [45]:
# 01_clean_311.sql
con.sql(
    open('sql/01_clean_311.sql').read()
).df()

,unique_key,created_date,closed_date,status,borough,community_board,incident_zip,address_type,latitude,longitude,borocd,is_jia,report_month,days_to_close
0,60738936,2024-03-31 19:28:50,NaT,Pending,QUEENS,07 QUEENS,11355,INTERSECTION,40.751802,-73.817310,407,False,2024-03-01,<NA>
1,60304555,2024-02-09 19:25:39,2024-02-09 21:47:00,Closed,QUEENS,11 QUEENS,11365,INTERSECTION,40.751895,-73.779806,411,False,2024-02-01,0
2,60422605,2024-02-26 15:49:00,2024-02-27 21:00:00,Closed,QUEENS,01 QUEENS,11101,INTERSECTION,40.752013,-73.930153,401,False,2024-02-01,1
3,59199024,2023-10-23 21:29:13,2023-10-24 13:55:00,Closed,MANHATTAN,06 MANHATTAN,10017,INTERSECTION,40.752064,-73.973504,106,False,2023-10-01,1
4,59762340,2023-12-16 15:14:48,2023-12-19 09:25:00,Closed,QUEENS,07 QUEENS,11355,INTERSECTION,40.752079,-73.810769,407,False,2023-12-01,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72635,59199020,2023-10-23 20:35:33,2023-10-29 05:05:00,Closed,BRONX,09 BRONX,10472,INTERSECTION,40.829502,-73.874609,209,False,2023-10-01,6
72636,63225730,2024-11-25 07:23:59,2024-11-26 09:30:00,Closed,BRONX,04 BRONX,10451,ADDRESS,40.829510,-73.929328,204,False,2024-11-01,1
72637,60769971,2024-04-04 14:55:52,2024-04-04 14:55:52,Closed,BRONX,04 BRONX,10452,INTERSECTION,40.829524,-73.924973,204,False,2024-04-01,0
72638,59307632,2023-11-02 14:30:58,2023-11-02 14:30:58,Closed,BRONX,09 BRONX,10472,INTERSECTION,40.829778,-73.850539,209,False,2023-11-01,0
72639,60841982,2024-04-12 08:36:08,2024-04-29 09:15:00,Closed,BRONX,03 BRONX,10456,INTERSECTION,40.829824,-73.907722,203,False,2024-04-01,17

In [46]:
# 02_clean_dot_repairs.sql
con.sql(
    open('sql/02_clean_dot_repairs.sql').read()
).df()

,onfacename,source,rptdate,rptclosed,centroid_lat,centroid_lon,borough,report_month,days_to_close
0,SECOR AV,CTZ,2024-03-27,2024-03-28,40.887341,-73.832412,BRONX,2024-03-01,1
1,BDWY,YRD,2023-03-06,2023-03-06,40.888494,-73.898749,BRONX,2023-03-01,0
2,E 227 ST,CTZ,2023-01-16,2023-01-17,40.888763,-73.858246,BRONX,2023-01-01,1
3,PALISADE AV,YRD,2023-02-08,2023-02-08,40.888979,-73.918187,BRONX,2023-02-01,0
4,E 231 ST,YRD,2023-03-16,2023-03-16,40.889755,-73.850931,BRONX,2023-03-01,0
...,...,...,...,...,...,...,...,...,...
32382,FIELDSTON RD,CTZ,2023-12-13,2023-12-14,40.910320,-73.899418,BRONX,2023-12-01,1
32383,W 262 ST,CTZ,2024-02-07,2024-02-08,40.910679,-73.897922,BRONX,2024-02-01,1
32384,W 261 ST,YRD,2023-01-27,2023-01-27,40.910714,-73.904888,BRONX,2023-01-01,0
32385,W 261 ST,CTZ,2024-01-10,2024-01-11,40.910714,-73.904888,BRONX,2024-01-01,1
32386,LIEBIG AV,CTZ,2024-04-10,2024-04-11,40.910948,-73.901092,BRONX,2024-04-01,1

In [49]:
# 03_join_to_districts.sql
con.sql(
    open('sql/03_join_to_districts.sql').read()
).df()

      borocd report_month  n_reports_311  n_repairs_dot
0        101   2023-01-01             47             13
1        101   2023-02-01             38             12
2        101   2023-03-01            124             43
3        101   2023-04-01             47             19
4        101   2023-05-01             45             21
...      ...          ...            ...            ...
1411     503   2024-08-01             69             32
1412     503   2024-09-01             62             32
1413     503   2024-10-01             57             24
1414     503   2024-11-01             40             25
1415     503   2024-12-01            133             67

[1416 rows x 4 columns]

In [50]:
# 04_attach_acs.sql
con.sql(
    open('sql/04_attach_acs.sql').read()
).df()

,borocd,report_month,n_reports_311,n_repairs_dot,total_population,median_age,median_household_income,pct_renters,rental_vacancy_rate,pct_with_college_degree,pct_foreign_born
0,101,2023-01-01,47,13,71865,35.000000,200000,70.099998,2.7,82.300003,25.0
1,101,2023-02-01,38,12,71865,35.000000,200000,70.099998,2.7,82.300003,25.0
2,101,2023-03-01,124,43,71865,35.000000,200000,70.099998,2.7,82.300003,25.0
3,101,2023-04-01,47,19,71865,35.000000,200000,70.099998,2.7,82.300003,25.0
4,101,2023-05-01,45,21,71865,35.000000,200000,70.099998,2.7,82.300003,25.0
...,...,...,...,...,...,...,...,...,...,...,...
1411,503,2024-08-01,69,32,168729,41.900002,118478,20.700001,5.2,39.799999,18.6
1412,503,2024-09-01,62,32,168729,41.900002,118478,20.700001,5.2,39.799999,18.6
1413,503,2024-10-01,57,24,168729,41.900002,118478,20.700001,5.2,39.799999,18.6
1414,503,2024-11-01,40,25,168729,41.900002,118478,20.700001,5.2,39.799999,18.6
1415,503,2024-12-01,133,67,168729,41.900002,118478,20.700001,5.2,39.799999,18.6

In [2]:
# 05_attach_road_miles.sql
con.sql(
    open('sql/05_attach_road_miles.sql').read()
).df()

,borocd,report_month,n_reports_311,n_repairs_dot,total_population,median_age,median_household_income,pct_renters,rental_vacancy_rate,pct_with_college_degree,pct_foreign_born,road_miles
0,101,2023-01-01,47,13,71865,35.000000,200000,70.099998,2.7,82.300003,25.0,51.636055
1,101,2023-02-01,38,12,71865,35.000000,200000,70.099998,2.7,82.300003,25.0,51.636055
2,101,2023-03-01,124,43,71865,35.000000,200000,70.099998,2.7,82.300003,25.0,51.636055
3,101,2023-04-01,47,19,71865,35.000000,200000,70.099998,2.7,82.300003,25.0,51.636055
4,101,2023-05-01,45,21,71865,35.000000,200000,70.099998,2.7,82.300003,25.0,51.636055
...,...,...,...,...,...,...,...,...,...,...,...,...
1411,503,2024-08-01,69,32,168729,41.900002,118478,20.700001,5.2,39.799999,18.6,393.392206
1412,503,2024-09-01,62,32,168729,41.900002,118478,20.700001,5.2,39.799999,18.6,393.392206
1413,503,2024-10-01,57,24,168729,41.900002,118478,20.700001,5.2,39.799999,18.6,393.392206
1414,503,2024-11-01,40,25,168729,41.900002,118478,20.700001,5.2,39.799999,18.6,393.392206
1415,503,2024-12-01,133,67,168729,41.900002,118478,20.700001,5.2,39.799999,18.6,393.392206

In [5]:
df = pd.read_parquet('data/final/analytical_table.parquet')
print(df.shape)         # should be 1,416 rows, 12 columns
print(df.dtypes)  
print(df.isna().sum())  # NULL audit on every column
print(df.describe())    # summary stats

(1416, 12)
borocd                              int64
report_month               datetime64[us]
n_reports_311                       int64
n_repairs_dot                       int64
total_population                    int32
median_age                        float32
median_household_income             int32
pct_renters                       float32
rental_vacancy_rate               float32
pct_with_college_degree           float32
pct_foreign_born                  float32
road_miles                        float64
dtype: object
borocd                     0
report_month               0
n_reports_311              0
n_repairs_dot              0
total_population           0
median_age                 0
median_household_income    0
pct_renters                0
rental_vacancy_rate        0
pct_with_college_degree    0
pct_foreign_born           0
road_miles                 0
dtype: int64
            borocd         report_month  n_reports_311  n_repairs_dot  \
count  1416.000000                 1416    1416.000000     1416.00000
mean    280.305085  2023-12-16 10:00:00      50.132768       22.77048
min     101.000000  2023-01-01 00:00:00       1.000000        0.00000
25%     203.000000  2023-06-23 12:00:00      23.000000       10.00000
50%     306.000000  2023-12-16 12:00:00      37.000000       17.00000
75%     403.000000  2024-06-08 12:00:00      64.000000       29.00000
max     503.000000  2024-12-01 00:00:00     371.000000      219.00000
std     117.799795                  NaN      44.066133       20.10570

       total_population   median_age  median_household_income  pct_renters  \
count       1416.000000  1416.000000              1416.000000  1416.000000
mean      144330.813559    38.144070             84640.169492    68.140678
min        51619.000000    28.900000             31296.000000    20.700001
25%       113982.000000    35.299999             65048.000000    59.099998
50%       136125.000000    38.099998             78010.000000    69.800003
75%       179054.000000    40.500000             95190.000000    83.500000
max       254693.000000    46.900002            200000.000000    95.699997
std        43253.240798     3.757149             37018.354226    18.117086

       rental_vacancy_rate  pct_with_college_degree  pct_foreign_born  \
count          1416.000000              1416.000000       1416.000000
mean              3.379661                40.618645         35.586441
min               1.200000                14.100000         17.799999
25%               2.300000                27.200001         26.000000
50%               3.200000                39.500000         33.000000
75%               4.000000                48.299999         44.799999
max               7.800000                84.400002         63.299999
std               1.565506                19.611055         11.180307

        road_miles
count  1416.000000
mean    117.145203
min      40.783731
25%      55.082872
50%      88.329626
75%     151.582624
max     393.392206
std      84.843796